export const getSubCategories1 = async () => {
    const url = "http://localhost:3000/subcategory?cat_id=1";
    try {
        const res = await fetch(url);
        const data = await res.json();
        return data;
    } catch (error) {
        console.error("Fetch error:", error);
        throw error;
    }
};
export const getSubCategories2 = async () => {
    const url = "http://localhost:3000/subcategory?cat_id=2";
    try {
        const res = await fetch(url);
        const data = await res.json();
        return data;
    } catch (error) {
        console.error("Fetch error:", error);
        throw error;
    }
};
export const getSubCategories3 = async () => {
    const url = "http://localhost:3000/subcategory?cat_id=3";
    try {
        const res = await fetch(url);
        const data = await res.json();
        return data;
    } catch (error) {
        console.error("Fetch error:", error);
        throw error;
    }
};
export const getSubCategories4 = async () => {
    const url = "http://localhost:3000/subcategory?cat_id=4";
    try {
        const res = await fetch(url);
        const data = await res.json();
        return data;
    } catch (error) {
        console.error("Fetch error:", error);
        throw error;
    }
};
export const getSubCategories5 = async () => {
    const url = "http://localhost:3000/subcategory?cat_id=5";
    try {
        const res = await fetch(url);
        const data = await res.json();
        return data;
    } catch (error) {
        console.error("Fetch error:", error);
        throw error;
    }
};
export const getSubCategories6 = async () => {
    const url = "http://localhost:3000/subcategory?cat_id=6";
    try {
        const res = await fetch(url);
        const data = await res.json();
        return data;
    } catch (error) {
        console.error("Fetch error:", error);
        throw error;
    }
};
export const getSubCategories7 = async () => {
    const url = "http://localhost:3000/subcategory?cat_id=7";
    try {
        const res = await fetch(url);
        const data = await res.json();
        return data;
    } catch (error) {
        console.error("Fetch error:", error);
        throw error;
    }
};
export const getSubCategories8 = async () => {
    const url = "http://localhost:3000/subcategory?cat_id=8";
    try {
        const res = await fetch(url);
        const data = await res.json();
        return data;
    } catch (error) {
        console.error("Fetch error:", error);
        throw error;
    }
};
export const getSubCategories9 = async () => {
    const url = "http://localhost:3000/subcategory?cat_id=9";
    try {
        const res = await fetch(url);
        const data = await res.json();
        return data;
    } catch (error) {
        console.error("Fetch error:", error);
        throw error;
    }
};
export const getSubCategories10 = async () => {
    const url = "http://localhost:3000/subcategory?cat_id=10";
    try {
        const res = await fetch(url);
        const data = await res.json();
        return data;
    } catch (error) {
        console.error("Fetch error:", error);
        throw error;
    }
};